import { AuthMenu } from './auth'

export const defaultMenu: Array<AuthMenu> = [
  {
    children: null,
    code: 'orderShipmentIndex',
    ext1: '/orderShipment/index',
    ext2: 'orderShipmentIndex',
    ext3: '打单发货',
    hasChild: false,
    icon: 'ux-icon-print',
    id: 1,
    level: 1,
    type: 0,
    url: null,
  },
  {
    code: 'electronicBill',
    ext1: '/electronicBill',
    ext2: 'electronicBill',
    ext3: '电子面单',
    hasChild: false,
    icon: 'ux-icon-document-copy',
    id: 2,
    level: 1,
    type: 0,
    children: [
      {
        code: 'serverExpressSheet',
        ext1: '/serverExpressSheet',
        ext2: 'serverExpressSheet',
        ext3: '服务商管理',
        hasChild: false,
        id: 21,
        level: 2,
        type: 0,
      },
      {
        code: 'applyServerProvider',
        ext1: '/serverExpressSheet/applyServerProvider',
        ext2: 'applyServerProvider',
        ext3: '申请服务商',
        hasChild: false,
        id: 22,
        level: 2,
        type: 2,
      },
    ],
    url: null,
  },
  {
    children: null,
    code: 'setFocus',
    ext1: '/setFocus',
    ext2: 'setFocus',
    ext3: '设置中心',
    hasChild: false,
    icon: 'ux-icon-manage',
    id: 3,
    level: 1,
    type: 0,
    url: null,
  },
]
